name: First Workflow

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v4

      - name: Run script
        run: |
          echo "Running script on $(date)"
          ls -la
