name: First Workflow

on: 
  push:
  pull_request:

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v4

  #     - name: Run script
  #       run: |
  #         echo "Running script on $(date)"
  #         ls -la

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]

    name: Node.js ${{ matrix.node }} test
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: node -v